version: 2.1

setup: true

orbs:
  config-splitting: circle-makotom-orbs/config-splitting@0.0.9

workflows:
  setup-config-files:
    jobs:
      # Specify the file listing configs to be combined in `config-list-file`
      # This job combines those listed configs, then execute the resulting config.
      - config-splitting/run-modular-configs-selectively:
          module-list-file: .circleci/subdir-list.txt
          base-revision: main # Compare against this branch


# VS Code Extension Version: 1.1.1